### ISSUE TITLE
ValueError 'too many values to unpack' while translation platform sync. 

### ISSUE THREAD

**Issue by spathare21** [transtats/transtats#134]
##### ISSUE TYPE

 - Bug Report
 
##### OS / ENVIRONMENT

```
Fedora 28 workstation
```

##### SUMMARY

We are getting ValueError while package translation platform sync

##### STEPS TO REPRODUCE
- Clone transtats repo
- Setup db using attached files
- Make transtats running 
- check packages sync action

```

```

##### EXPECTED RESULTS
- Translation platform Sync should get completed

##### ACTUAL RESULTS
 - Getting valueError "too many values to unpack"

[transtats_db_json.zip](https://github.com/transtats/transtats/files/2114742/transtats_db_json.zip)

**Comment by sundeep-co-in** [comment]
This is happening because we are using same alias for some locaes.
For example:  `ar` for three locales: `ar-eg`, `ar-qa`, `ar-sa`
Thanks @spathare21 catching this up!! 

Actually, alias can be `null` and hence should only be used if required. 
Will try to fix this in https://github.com/transtats/transtats/pull/132 (Planned for `release_0.1.6`)
So basically _(locales and their aliases should be unique)_ we may have something like:

|  locale               |  alias       |  script        |
| -------------------- | ------------ | -------------- |
|  `sr_RS`           |  `sr`          |  Cyrl          |
|  `sr_RS@latin` | `sr@latin` |  Latn         |
|  `en_US`          | `en`          |  Latn          |
|  `en_GB`          |                 |  Latn          |
|  `pa_IN`           |  `pa`         |  Guru         |
|  `pa_PK`          |                 |  Arab          |

Please see https://raw.githubusercontent.com/mike-fabian/langtable/master/data/languages.xml

Hope this helps!

**Comment by spathare21** [comment]
@sundeep-co-in updated db 
[transtats_new_db.zip](https://github.com/transtats/transtats/files/2127189/transtats_new_db.zip)

**Comment by spathare21** [comment]
[lang_new.zip](https://github.com/transtats/transtats/files/2127475/lang_new.zip)

**Comment by spathare21** [comment]
Release summary shows 0 value for all languages 
![screenshot from 2018-06-22 19-21-26](https://user-images.githubusercontent.com/23230884/41780177-a707baee-7651-11e8-8d67-05b4cc45c088.png)

**Comment by sundeep-co-in** [comment]
this has been fixed in https://github.com/transtats/transtats/releases/tag/0.1.6-rc.1
@spathare21 Please ensure, language-set and release-branch mapping.

**Comment by sundeep-co-in** [comment]
thanks @spathare21
